In [1]:
import sklearn
import numpy as np
import pandas as pd
from sklearn import datasets, preprocessing, neighbors
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, accuracy_score

In [20]:
X = np.random.random((10,5))
print(X)
y = np.array(['M','M','F','F','M','F','M','M','F','F','F'])
X[X < 0.7] = 0
print(X)

[[0.17992561 0.04017489 0.15825491 0.24033653 0.74481633]
 [0.90528764 0.47094012 0.88491334 0.19574415 0.42546238]
 [0.88150776 0.16358637 0.86155775 0.23237864 0.23227384]
 [0.95148896 0.40984959 0.47231186 0.35540971 0.72033253]
 [0.85111496 0.08661515 0.53085155 0.45602299 0.57964898]
 [0.24282997 0.01078629 0.7116675  0.19727987 0.61699027]
 [0.11214474 0.36156086 0.85891055 0.3386257  0.63812965]
 [0.58049492 0.43896946 0.41410094 0.46361634 0.21007385]
 [0.67759274 0.84703613 0.4164648  0.1999097  0.8115341 ]
 [0.01243804 0.58174163 0.00568377 0.59329069 0.8697195 ]]
[[0.         0.         0.         0.         0.74481633]
 [0.90528764 0.         0.88491334 0.         0.        ]
 [0.88150776 0.         0.86155775 0.         0.        ]
 [0.95148896 0.         0.         0.         0.72033253]
 [0.85111496 0.         0.         0.         0.        ]
 [0.         0.         0.7116675  0.         0.        ]
 [0.         0.         0.85891055 0.         0.        ]
 [0.         