In [1]:
import numpy as np
import pandas as pd

In [8]:
a = np.random.rand(4,5)
print(a, a[1,1])
df = pd.DataFrame(a)
print(df,df[1][1])
c = np.random.randint(5, size = (4,5))
print(c)
df1 = pd.DataFrame(c)
print(df1)

[[0.17999312 0.25840146 0.00960637 0.49634311 0.71682702]
 [0.64869971 0.38033501 0.18712691 0.6038806  0.50606236]
 [0.59726146 0.55735435 0.37350379 0.03525737 0.59909162]
 [0.81882907 0.95495532 0.85051647 0.19315144 0.1397882 ]] 0.3803350050181489
          0         1         2         3         4
0  0.179993  0.258401  0.009606  0.496343  0.716827
1  0.648700  0.380335  0.187127  0.603881  0.506062
2  0.597261  0.557354  0.373504  0.035257  0.599092
3  0.818829  0.954955  0.850516  0.193151  0.139788 0.3803350050181489
[[2 3 2 2 4]
 [1 3 3 3 1]
 [0 1 0 4 3]
 [0 3 2 3 2]]
   0  1  2  3  4
0  2  3  2  2  4
1  1  3  3  3  1
2  0  1  0  4  3
3  0  3  2  3  2


In [13]:
array1 = np.array([10, 20, 30, 40])
print(type(array1))
list1 = [10, "hello", 3.14, True]
print(type(list1))
pd.Series(list1)

<class 'numpy.ndarray'>
<class 'list'>


0       10
1    hello
2     3.14
3     True
dtype: object

In [21]:
df = pd.date_range('2026/3/30',periods=df.shape[0])
print(df)

DatetimeIndex(['2026-03-30', '2026-03-31', '2026-04-01', '2026-04-02'], dtype='datetime64[ns]', freq='D')
