In [1]:
import numpy as np

In [3]:
np.loadtxt(r"H:\MLOPS\MLOPS-Python\01_numpy\numpy_text_practice.txt")

array([0.7 , 0.75, 1.85, 2.93, 3.05, 2.02, 1.93, 1.62, 1.84, 1.31, 1.39,
       0.84])

In [7]:
np.genfromtxt(r"H:\MLOPS\MLOPS-Python\01_numpy\numpy_practice.csv", delimiter=',')

array([[ 1.07,  0.44,  1.5 ,  0.2 ,  3.2 ,  1.18,  0.09,  1.44,  1.52,
         2.44,  0.78,  0.02],
       [ 0.27,  1.13,  1.72,  4.14,  2.66,  0.61,  1.03,  1.4 , 18.16,
         2.24,  0.29,  0.5 ]])

In [13]:
arr = np.arange(10)
print(arr)
# over writing
np.savetxt(r"H:\MLOPS\MLOPS-Python\01_numpy\numpy_text_practice.txt",arr,fmt= '%.2f', delimiter=',')
# appending
with open(r"H:\MLOPS\MLOPS-Python\01_numpy\avg-monthly-precip.txt",'a') as f:
    np.savetxt(f,arr,fmt= '%.2f',delimiter=',')

[0 1 2 3 4 5 6 7 8 9]


In [15]:
arr = np.arange(10)
print(arr)
# over writing
np.savetxt(r"H:\MLOPS\MLOPS-Python\01_numpy\numpy_practice.csv",arr,delimiter=',')
# appending
with open(r'H:\MLOPS\MLOPS-Python\01_numpy\numpy_tut.csv','a') as f:
    np.savetxt(f,arr,fmt = '%.2f', delimiter=',')

[0 1 2 3 4 5 6 7 8 9]
