In [1]:
import numpy as np

In [ ]:
# Create a 1D array
onedim_array =  np.array([1, 2, 3])
print(onedim_array)
# Create a 2D array
twodim_array =  np.array([(1,2),(3,4)])
print(twodim_array)
# Create a 3D array
# 3 layers, 2 rows, 4 columns
threedim_array =  np.array([
    [[1, 2, 3 ,4], [4, 5,1,2]],
    [[7, 8,5,6], [10, 11,6,7]],
    [[13, 18,7,8], [20, 21, 7, 8]]
])
print(threedim_array.shape)
print(threedim_array)

[1 2 3]
[[1 2]
 [3 4]]
(3, 2, 4)
[[[ 1  2  3  4]
  [ 4  5  1  2]]

 [[ 7  8  5  6]
  [10 11  6  7]]

 [[13 18  7  8]
  [20 21  7  8]]]


In [ ]:
# 4D Array (blocks, layers, rows, columns)
# deep learning (e.g., CNNs): Usually you see 4D → (batch, channels, height, width)
import numpy as np

arr4d = np.array([
    [  # Block 1
        [  # Layer 1
            [1, 2], [3, 4], [5, 6], [7, 8]
        ],
        [  # Layer 2
            [9, 10], [11, 12], [13, 14], [15, 16]
        ]
    ],
    [  # Block 2
        [
            [17, 18], [19, 20], [21, 22], [23, 24]
        ],
        [
            [25, 26], [27, 28], [29, 30], [31, 32]
        ]
    ],
    [  # Block 3
        [
            [33, 34], [35, 36], [37, 38], [39, 40]
        ],
        [
            [41, 42], [43, 44], [45, 46], [47, 48]
        ]
    ]
])

print(arr4d.shape)

(3, 2, 4, 2)


In [12]:
# 5D batch → channels → height → width → features
import numpy as np
arr5d = np.arange(2*3*4*4*2).reshape(2, 3, 4, 4, 2)
print(arr5d.shape)
# 2 batches → 2 samples (e.g., 2 images)
# 3 channels → like RGB
# 4 × 4 → image size
# 2 features per pixel → extra info per pixel

(2, 3, 4, 4, 2)


In [19]:
zero_array = np.zeros(3)
print(zero_array)
ones_array = np.ones((4,5))
print(ones_array)
eye_array = np.eye(5)
print(eye_array)


[0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
lin_array = np.linspace(0,100,5) #(start, end, divisions)
print(lin_array)
step_array = np.arange(0,10,2)
print(step_array)
full_array = np.full((3,4),5)
print(full_array)

[  0.  25.  50.  75. 100.]
[0 2 4 6 8]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [33]:
#  random floats between 0 and 1
rand_array = np.random.rand(4,5)
print(rand_array)
#  random floats between 0 and 10
rand1_array = np.random.rand(4,5)*10
print(rand1_array)
# integer value between 0 to 4
rand2_array = np.random.randint(4, size= (2,3))
print(rand2_array)

[[0.6286512  0.20677147 0.47458365 0.37926777 0.71375845]
 [0.66281482 0.22597661 0.70992419 0.35440484 0.02235838]
 [0.58746791 0.58445584 0.67768458 0.8863046  0.41454283]
 [0.9478483  0.28174233 0.52472149 0.48075513 0.77023451]]
[[3.32456969 2.17079239 3.16709814 2.0224136  6.13952153]
 [5.99652454 9.94666061 2.39003353 5.1333397  1.67124025]
 [6.69868998 0.62696241 3.87925965 9.68675886 9.98672641]
 [7.08133394 0.16265112 9.65434867 0.64888297 0.27873021]]
[[3 1 3]
 [0 3 0]]
