In [1]:
import numpy as np

In [11]:
a = np.arange(1,10,2)
print(a)
print(type(a))
print(a.dtype)
# float
b = a.astype(float)
print(b)
print(type(b))
print(b.dtype)
# string
c = a.astype(str)
print(c)
print(c.dtype)
# boolean
d = a.astype(bool)
print(d)
print(d.dtype)
# others
for dtype in [np.int8, np.int16, np.float32, np.float16, np.float32, np.float64, np.bool_]:
    print(dtype, a.astype(dtype).dtype)

[1 3 5 7 9]
<class 'numpy.ndarray'>
int32
[1. 3. 5. 7. 9.]
<class 'numpy.ndarray'>
float64
['1' '3' '5' '7' '9']
<U11
[ True  True  True  True  True]
bool
<class 'numpy.int8'> int8
<class 'numpy.int16'> int16
<class 'numpy.float32'> float32
<class 'numpy.float16'> float16
<class 'numpy.float32'> float32
<class 'numpy.float64'> float64
<class 'numpy.bool_'> bool


In [14]:
arr = np.random.randint(3, size = (4,5))
print(arr.size)
print(arr.shape)
print(arr.dtype)
print(arr.reshape(2,10))

20
(4, 5)
int32
[[2 1 2 1 0 0 1 1 2 2]
 [0 1 0 1 2 2 2 2 1 2]]
