In [1]:
import numpy as np

In [6]:
arr =  np.array([1, 2, 3, 4])
# copy
b = np.copy(arr)
print ("arr,b",arr,b)
b[1] = 100
print("No change in arr",arr)
# assignment
c = arr
c[1] = 100
print("arr changed",arr)

arr,b [1 2 3 4] [1 2 3 4]
No change in arr [1 2 3 4]
arr changed [  1 100   3   4]


In [15]:
arr = np.array([1, 2, 3, 4], dtype=np.int16)
b = arr.view(np.float16)
print(arr)
print(b)

[1 2 3 4]
[6.0e-08 1.2e-07 1.8e-07 2.4e-07]


In [19]:
arr = np.random.randint(10, size = 10)
print(arr)
print(np.sort(arr))

[2 4 3 6 0 7 1 5 0 2]
[0 0 1 2 2 3 4 5 6 7]


In [25]:
arr = np.random.randint(10, size = (2,10))
print(arr)
print(arr.sort(axis=1))
print(arr.flatten())

[[4 8 4 2 5 2 4 6 9 7]
 [3 3 1 0 8 5 8 8 1 5]]
None
[2 2 4 4 4 5 6 7 8 9 0 1 1 3 3 5 5 8 8 8]


In [42]:
a =  np.random.randint(9, size = (4,6))
print(a)
b = a.T
print(b)
C = a.reshape(2,12)
print(C)
del b
del C
d = a.resize((4,4))
print(d)
print("modified matrix \n",a)
e = np.resize(a,(10,7))
print(e)

[[6 5 0 4 8 2]
 [2 1 7 5 4 3]
 [0 1 3 5 4 1]
 [7 1 8 1 5 4]]
[[6 2 0 7]
 [5 1 1 1]
 [0 7 3 8]
 [4 5 5 1]
 [8 4 4 5]
 [2 3 1 4]]
[[6 5 0 4 8 2 2 1 7 5 4 3]
 [0 1 3 5 4 1 7 1 8 1 5 4]]
None
modified matrix 
 [[6 5 0 4]
 [8 2 2 1]
 [7 5 4 3]
 [0 1 3 5]]
[[6 5 0 4 8 2 2]
 [1 7 5 4 3 0 1]
 [3 5 6 5 0 4 8]
 [2 2 1 7 5 4 3]
 [0 1 3 5 6 5 0]
 [4 8 2 2 1 7 5]
 [4 3 0 1 3 5 6]
 [5 0 4 8 2 2 1]
 [7 5 4 3 0 1 3]
 [5 6 5 0 4 8 2]]
