In [1]:
import numpy as np

In [5]:
a = np.array([[1,2,4], [4,6,7]])
print(a)
b = np.append(a, [1,6,7])
print(b)

[[1 2 4]
 [4 6 7]]
[1 2 4 4 6 7 1 6 7]


In [ ]:
a = np.array([[1,2,4], [4,6,7]])
print(a)
#  Inserts values into a before index 2
b =  np.insert(a,2,[9,8,7])
print(b)

[[1 2 4]
 [4 6 7]]
[1 2 9 8 7 4 4 6 7]


In [11]:
print(a)
# Deletes row on index 0 of a
d = np.delete(a, 0, axis=0)
print(d)

[[1 2 4]
 [4 6 7]]
[[4 6 7]]
