In [1]:
import numpy as np

In [11]:
a =  np.random.randint(5, size = (3,4))
b =  np.random.randint(3, size = (5,6))
print(a)
print(b)
c = np.resize(a,(5,6))
print(c)
# add rows c at the end of b
con_row = np.concatenate((b, c), axis = 0)
print(con_row)
# add columns c at the end of b
con_col = np.concatenate((b, c), axis = 1)
print(con_col)

[[1 3 4 2]
 [3 2 3 4]
 [0 2 4 1]]
[[1 0 1 2 2 0]
 [1 0 2 1 2 1]
 [1 2 1 0 2 0]
 [2 1 1 1 2 1]
 [1 0 0 2 1 0]]
[[1 3 4 2 3 2]
 [3 4 0 2 4 1]
 [1 3 4 2 3 2]
 [3 4 0 2 4 1]
 [1 3 4 2 3 2]]
[[1 0 1 2 2 0]
 [1 0 2 1 2 1]
 [1 2 1 0 2 0]
 [2 1 1 1 2 1]
 [1 0 0 2 1 0]
 [1 3 4 2 3 2]
 [3 4 0 2 4 1]
 [1 3 4 2 3 2]
 [3 4 0 2 4 1]
 [1 3 4 2 3 2]]
[[1 0 1 2 2 0 1 3 4 2 3 2]
 [1 0 2 1 2 1 3 4 0 2 4 1]
 [1 2 1 0 2 0 1 3 4 2 3 2]
 [2 1 1 1 2 1 3 4 0 2 4 1]
 [1 0 0 2 1 0 1 3 4 2 3 2]]


In [ ]:
# split
a =  np.random.randint(5, size = (3,4))
print(a)
# split into 3(rows) sub-arrays
split_arr = np.split(a,3) 
print(split_arr)

[[1 3 1 3]
 [0 2 2 0]
 [1 1 2 4]]
[array([[1, 3, 1, 3]]), array([[0, 2, 2, 0]]), array([[1, 1, 2, 4]])]


In [23]:
b =  np.random.randint(3, size = (5,6))
print(b)
# split into 6(column) sub-arrays
hor_split = np.hsplit(b,6)
print(hor_split)

[[2 0 1 0 0 2]
 [0 1 1 1 1 1]
 [1 0 2 0 1 2]
 [0 2 1 0 0 1]
 [1 2 2 1 0 1]]
[array([[2],
       [0],
       [1],
       [0],
       [1]]), array([[0],
       [1],
       [0],
       [2],
       [2]]), array([[1],
       [1],
       [2],
       [1],
       [2]]), array([[0],
       [1],
       [0],
       [0],
       [1]]), array([[0],
       [1],
       [1],
       [0],
       [0]]), array([[2],
       [1],
       [2],
       [1],
       [1]])]


In [ ]:
c = np.array([[1,2,3,10],[4,5,6,12],[8,9,10,11],[14,15,16,2],])
print(c)
print(c[:,1:3]) #columns
print(c[0:2,:]) # rows
print(c[:,-1]) # last column
print(c[-1,:]) # last row
print(c[:,-3:-1]) # -3, -2 column

[[ 1  2  3 10]
 [ 4  5  6 12]
 [ 8  9 10 11]
 [14 15 16  2]]
[[ 2  3]
 [ 5  6]
 [ 9 10]
 [15 16]]
[[ 1  2  3 10]
 [ 4  5  6 12]]
[10 12 11  2]
[14 15 16  2]
[[ 2  3]
 [ 5  6]
 [ 9 10]
 [15 16]]


In [64]:
c = np.random.randint(5, size=(3,15))
print("c\n",c)
# first three columns
print(f"first three columns \n {c[:,0:3]}")
# last three columns -1,-2,-3
print(c[:,-3:])
# only last column
print(c[:,-1])

c
 [[3 3 1 3 4 1 2 0 4 1 0 3 4 0 1]
 [2 4 1 1 3 2 4 3 2 4 0 1 2 4 1]
 [3 4 2 4 3 3 2 2 0 1 1 0 3 3 2]]
first three columns 
 [[3 3 1]
 [2 4 1]
 [3 4 2]]
[[4 0 1]
 [2 4 1]
 [3 3 2]]
[1 1 2]


In [67]:
d = np.random.randint(5, size=(10,5))
print("d\n",d)
# firt 4 rows
print(f"firt 4 rows \n{d[0:4,:]}")
# last 4 columns
print(f"last 4 columns \n {d[-4:,:]}")
# last coulmn
print(f"last column \n{d[-1,:]}")

d
 [[1 3 4 0 1]
 [3 0 0 1 2]
 [2 1 3 0 2]
 [2 2 3 2 3]
 [3 1 3 3 4]
 [4 3 0 1 3]
 [3 0 2 0 1]
 [2 4 2 1 2]
 [4 1 2 0 1]
 [4 1 2 0 0]]
firt 4 rows 
[[1 3 4 0 1]
 [3 0 0 1 2]
 [2 1 3 0 2]
 [2 2 3 2 3]]
last 4 columns 
 [[3 0 2 0 1]
 [2 4 2 1 2]
 [4 1 2 0 1]
 [4 1 2 0 0]]
last column 
[4 1 2 0 0]


In [74]:
# specific element
e = np.random.randint(5, size=(8,5))
print("e\n",e)

# last but three rows and last but 2 columns
print(f"last but three rows \n {e[-4:-1, :]}")
print(f"last but 2 columns \n {e[:, -3:-1]}")
print(f"last but three rows and last but 2 columns \n {e[-4:-1, -3:-1]}")


e
 [[4 3 0 1 3]
 [2 1 3 2 1]
 [4 3 2 0 4]
 [3 3 0 3 2]
 [0 4 1 4 4]
 [1 4 0 4 4]
 [4 2 0 2 1]
 [0 0 0 3 1]]
last but three rows 
 [[0 4 1 4 4]
 [1 4 0 4 4]
 [4 2 0 2 1]]
last but 2 columns 
 [[0 1]
 [3 2]
 [2 0]
 [0 3]
 [1 4]
 [0 4]
 [0 2]
 [0 3]]
last but three rows and last but 2 columns 
 [[1 4]
 [0 4]
 [0 2]]
