In [1]:
import numpy as np

In [16]:
# Indexing
arr = np.random.randint(6, size = (4,5))
print(arr)
print(arr[2]) # 3rd row (elements of 3rd index)
print(arr[2][3]) # 3rd row, 4th column
print(arr[2,3])


[[5 5 0 2 3]
 [3 0 2 0 0]
 [2 2 0 4 3]
 [1 1 4 1 4]]
[2 2 0 4 3]
4
4


In [26]:
# Slicing
arr = np.random.randint(6, size = (5,5))
print(arr)
print(arr[1:4]) # Index of 1,2,3
print(arr[1:4,2]) # rows of 1,2,3 and column of 2
print(arr[1:4,2:3])
print(arr[:2]) # 0,1 rows
print(arr[3:]) # 3,4 rows
print(arr[:,3:]) # 3,4 columns
print(arr[:,1:3]) # 1,2 colums



[[1 3 0 4 3]
 [4 2 1 2 3]
 [2 5 5 2 3]
 [2 3 5 4 0]
 [0 0 4 3 5]]
[[4 2 1 2 3]
 [2 5 5 2 3]
 [2 3 5 4 0]]
[1 5 5]
[[1]
 [5]
 [5]]
[[1 3 0 4 3]
 [4 2 1 2 3]]
[[2 3 5 4 0]
 [0 0 4 3 5]]
[[4 3]
 [2 3]
 [2 3]
 [4 0]
 [3 5]]
[[3 0]
 [2 1]
 [5 5]
 [3 5]
 [0 4]]


In [33]:
# Conditional stmts
arr = np.random.randint(6, size = (5,5))
print(arr)
print(arr<4)

[[1 3 3 2 1]
 [5 0 0 1 4]
 [0 1 0 2 4]
 [3 4 3 0 2]
 [1 5 1 0 0]]
[[ True  True  True  True  True]
 [False  True  True  True False]
 [ True  True  True  True False]
 [ True False  True  True  True]
 [ True False  True  True  True]]


In [44]:
a = np.random.randint(4, size = (5,5))
b = np.random.randint(6, size = (5,5))
print(a)
print(~a)
print(b)
# and condition
print((a<2) & (b>3))
# or condition
print((a < 2) | (b > 3))

[[1 3 2 3 0]
 [1 2 3 1 1]
 [3 3 0 0 3]
 [2 2 1 3 1]
 [2 3 3 1 0]]
[[-2 -4 -3 -4 -1]
 [-2 -3 -4 -2 -2]
 [-4 -4 -1 -1 -4]
 [-3 -3 -2 -4 -2]
 [-3 -4 -4 -2 -1]]
[[1 1 2 2 1]
 [5 2 2 3 3]
 [4 5 3 0 3]
 [5 5 2 1 2]
 [3 4 0 2 2]]
[[False False False False False]
 [ True False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
[[ True False False False  True]
 [ True False False  True  True]
 [ True  True  True  True False]
 [ True  True  True False  True]
 [False  True False  True  True]]


In [42]:
arr = np.random.randint(5, size = (3,4))
print(arr)
print(arr[arr<3])

[[0 4 3 3]
 [1 4 3 4]
 [4 3 0 4]]
[0 1 0]
