In [2]:
import numpy as np

In [ ]:
# scalar math
a = np.array([1,2,4])
print(a)
print(np.add(a,1))
print(np.subtract(a,2))
print(np.multiply(a,2))
print(np.divide(a,2))
print(np.divmod(a,2))
print(np.power(a,3))
print(np.exp(a))
print(np.log10(a))
print(np.log2(a))

[1 2 4]
[2 3 5]
[-1  0  2]
[2 4 8]
[0.5 1.  2. ]
(array([0, 1, 2], dtype=int32), array([1, 0, 0], dtype=int32))
[ 1  8 64]
[ 2.71828183  7.3890561  54.59815003]
[0.         0.30103    0.60205999]
[0. 1. 2.]


In [11]:
# vector math
a = np.random.rand(5,6)
print(a)
b =  np.random.randint(5, size = (5,6))
print(b)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))


[[0.70021937 0.02864906 0.87759071 0.29744626 0.26929617 0.6412522 ]
 [0.46476322 0.05048172 0.74684669 0.29348815 0.27170609 0.11632383]
 [0.7470344  0.22041855 0.71102796 0.38626867 0.59752825 0.19097814]
 [0.75576853 0.97586167 0.37648199 0.3646384  0.96141969 0.3767775 ]
 [0.85749037 0.81219834 0.77965757 0.54108523 0.79905493 0.65411167]]
[[3 4 1 4 2 4]
 [0 4 1 1 3 4]
 [1 3 1 1 1 1]
 [4 3 1 2 2 1]
 [2 0 1 4 2 2]]
[[3.70021937 4.02864906 1.87759071 4.29744626 2.26929617 4.6412522 ]
 [0.46476322 4.05048172 1.74684669 1.29348815 3.27170609 4.11632383]
 [1.7470344  3.22041855 1.71102796 1.38626867 1.59752825 1.19097814]
 [4.75576853 3.97586167 1.37648199 2.3646384  2.96141969 1.3767775 ]
 [2.85749037 0.81219834 1.77965757 4.54108523 2.79905493 2.65411167]]
[[-2.29978063 -3.97135094 -0.12240929 -3.70255374 -1.73070383 -3.3587478 ]
 [ 0.46476322 -3.94951828 -0.25315331 -0.70651185 -2.72829391 -3.88367617]
 [-0.2529656  -2.77958145 -0.28897204 -0.61373133 -0.40247175 -0.80902186]
 [-3.24

In [14]:
a = np.random.rand(5,6)
print(a)
b =  np.random.randint(5, size = (5,6))
print(b)
print(np.divide(a,b))
print(np.power(a,b))
print(np.array_equal(a,b))

[[0.76193777 0.55053172 0.99741251 0.02685285 0.27082904 0.47644042]
 [0.24917573 0.59964177 0.30949586 0.50083354 0.80204556 0.51983157]
 [0.75313743 0.18111676 0.63747339 0.67345482 0.24884571 0.8914335 ]
 [0.22346323 0.49994919 0.17985723 0.95668804 0.93189108 0.43308546]
 [0.06269389 0.99840785 0.35894744 0.24560837 0.51824207 0.23596246]]
[[4 0 4 1 0 2]
 [4 2 2 1 1 1]
 [4 1 1 2 0 4]
 [0 4 4 2 0 0]
 [0 1 4 4 3 0]]
[[0.19048444        inf 0.24935313 0.02685285        inf 0.23822021]
 [0.06229393 0.29982089 0.15474793 0.50083354 0.80204556 0.51983157]
 [0.18828436 0.18111676 0.63747339 0.33672741        inf 0.22285837]
 [       inf 0.1249873  0.04496431 0.47834402        inf        inf]
 [       inf 0.99840785 0.08973686 0.06140209 0.17274736        inf]]
[[0.33703733 1.         0.98969014 0.02685285 1.         0.22699547]
 [0.00385499 0.35957026 0.09578769 0.50083354 0.80204556 0.51983157]
 [0.32173397 0.18111676 0.63747339 0.4535414  1.         0.63147448]
 [1.         0.0624746  0

C:\Users\email\AppData\Local\Temp\ipykernel_33552\3256566472.py:5: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(a,b))


In [24]:
a =  np.array([2,3,4])
print(np.sqrt(a))
print(np.square(a))
print(np.sin(a))
print(np.log(a))
b = np.array([2+3j])
print(b)
print(np.abs(b))
print(abs(b))

[1.41421356 1.73205081 2.        ]
[ 4  9 16]
[ 0.90929743  0.14112001 -0.7568025 ]
[0.69314718 1.09861229 1.38629436]
[2.+3.j]
[3.60555128]
[3.60555128]


In [33]:
c = np.array([2.59])
print(c)
print(np.ceil(c))
print(np.floor(c))
print(np.round(c))

[2.59]
[3.]
[2.]
[3.]
