In [1]:
import numpy as np

In [ ]:
# Q1: Create a NumPy array [1,2,3,4,5]. Find its shape and size.
numpy_array = np.arange(1,6,1)
print(f"Numpy array details: {numpy_array}")
print(f"Shape of array: {np.shape(numpy_array)}")
print(f"Size of array: {np.size(numpy_array)}")

Numpy array details: [1 2 3 4 5]
Shape of array: (5,)
Size of array: 5


In [105]:
# Q2: Create a 3x3 array of zeros and convert it to float
np_zeros = np.zeros((3,3))
print(f"3 by 3 array:\n{np_zeros}")

# corrected
np_zeros = np.zeros((3,3)).astype(float)
print(f"3 by 3 array:\n{np_zeros}")



3 by 3 array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
3 by 3 array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# Q3: Generate [0,2,4,6,8] using a NumPy function.
num_array = np.arange(0,10,2)
print(num_array)

[0 2 4 6 8]


In [18]:
# Q4: Create a 2x3 array filled with 7. Replace element at (1,2) with 99
arr = np.full((2,3),7)
print(arr)
arr[1,2] = 99
print(arr)

[[7 7 7]
 [7 7 7]]
[[ 7  7  7]
 [ 7  7 99]]


In [106]:
# Q5: Given arr=[10,20,30,40,50]: slice index 1 to 3, replace values >30 with 0
arr=[10,20,30,40,50]
print(arr[1:4])
for i in range (len(arr)):
    if arr[i] >30:
        arr[i] = 0
print(arr)
# Corrected
arr = np.array([10,20,30,40,50])
arr[arr > 30] = 0

[20, 30, 40]
[10, 20, 30, 0, 0]


In [ ]:
# Q6: Given a=[1,2,3], b=[4,5,6]: multiply element-wise, then take sqrt
a=[1,2,3]
b=[4,5,6]
c = np.multiply(a,b)
print(f"element multiple:{c}")
d = np.sqrt(c)
print(f"Square root: {d}:")

element multiple:[ 4 10 18]
Square root: [2.         3.16227766 4.24264069]:.4f


In [108]:
# Q7: Create 4x4 random array. Find mean and column-wise max.
random_array = np.random.randint(4,size = (4,4))
print(f"random_array: \n{random_array}")
# correct
print(random_array.mean())
print(random_array.max())

mean_array = np.zeros(4)
column_max = np.zeros(4)
for i in range(len(random_array)):
    mean_array[i] = np.mean(random_array[:,i])
    column_max[i] = np.max(random_array[:,i])
print(f"mean value:{mean_array}")
print(f"max value:{column_max}")



random_array: 
[[1 2 3 2]
 [1 3 2 3]
 [0 3 3 2]
 [1 1 3 1]]
1.9375
3
mean value:[0.75 2.25 2.75 2.  ]
max value:[1. 3. 3. 3.]


In [49]:
# Q8: Given [[1,2,3],[4,5,6]]: transpose and flatten
A = np.array([[1,2,3],[4,5,6]])
B = A.T
print(f"Transpose of A:\n {B}")
print(f"Flatten of B:\n {B.flatten()}")


Transpose of A:
 [[1 4]
 [2 5]
 [3 6]]
Flatten of B:
 [1 4 2 5 3 6]


In [110]:
# Q9: Given [2,4,6,8,10]: boolean mask >5, extract and square them.
Arr = np.arange(2,12,2)
print(Arr)
filter = Arr > 5
filter_array = Arr[filter]
sq = np.square(filter_array)
print(sq)
Arr[filter] = Arr[filter]**2
print(Arr)


[ 2  4  6  8 10]
[ 36  64 100]
[  2   4  36  64 100]


In [65]:
# Q10: arange(1,13): reshape to 3x4, get 2nd row, last column, subarray (2x2).
ar = np.arange(1,13)
print(ar,len(ar))
ar_reshape = ar.reshape(3,4)
print(ar_reshape)
# second row
print(f"second row: {ar_reshape[1,:]}")
print(f"last column: {ar_reshape[:,-1]}")
print(f"sub array 2x2:\n {ar_reshape[:2,:2]}")

[ 1  2  3  4  5  6  7  8  9 10 11 12] 12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
second row: [5 6 7 8]
last column: [ 4  8 12]
sub array 2x2:
 [[1 2]
 [5 6]]


In [91]:
# Q11: Concatenate [[1,2],[3,4]] and [[5,6]] row-wise and column-wise.
a = [[1,2],[3,4]]
b = [[5,6]]
print(a,np.shape(a))
print(b,np.shape(b))
row_con = np.concatenate((a,b), axis = 0)
print(row_con)


[[1, 2], [3, 4]] (2, 2)
[[5, 6]] (1, 2)
[[1 2]
 [3 4]
 [5 6]]


In [112]:
# Q12: Given [10,25,30,45,50,5]: filter 20–50, replace <20 with -1, find mean & std.
a = np.array([10,25,30,45,50,5])
for i in range(len(a)):
    if a[i]<20:
        a[i] = -1
print(a)
print(f"mean and standard deviation are: {np.mean(a), np.std(a)}")
filtered = a[(a >= 20) & (a <= 50)]
print(filtered)


[-1 25 30 45 50 -1]
mean and standard deviation are: (24.666666666666668, 20.00555478416488)
[25 30 45 50]
